modLoader="kotlinforforge"
loaderVersion="[5.6,)"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://github.com/mykodb/server_expansion"
    logoFile=""
    credits="NeoForge,Kotlin For Forge"
    authors="${mod_authors}"
    description='''这是一个服务端的模组，为服务端实现了一些扩展功能。'''

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"